import type { BlockType } from './block-type'

export const ITEM_TYPES = [
  'stone',
  'cobblestone',
  'dirt',
  'grass_block',
  'sand',
  'gravel',
  'oak_log',
  'oak_planks',
  'oak_leaves',
  'glass',
  'clay',
  'brick',
  'torch',
  'glowstone',
  'piston',
  'stick',
  'glowstone_dust',
  'wooden_pickaxe',
  'coal',
  'coal_ore',
  'deepslate_coal_ore',
  'iron_ingot',
  'iron_ore',
  'deepslate_iron_ore',
  'gold_ingot',
  'gold_ore',
  'deepslate_gold_ore',
  'diamond_ore',
  'deepslate_diamond_ore',
  'redstone_ore',
  'deepslate_redstone_ore',
  'lapis_ore',
  'deepslate_lapis_ore',
  'emerald_ore',
  'deepslate_emerald_ore',
  'flint',
  'gunpowder',
  'blaze_powder',
  'flint_and_steel',
  'fire_charge',
  'granite',
  'diorite',
  'andesite',
  'deepslate',
  'obsidian',
  'smooth_basalt',
  'calcite',
  'amethyst_block',
  'sandstone',
  'prismarine',
  'soul_sand',
  'coal_block',
  'iron_block',
  'gold_block',
  'diamond_block',
  'redstone_block',
  'lapis_block',
  'emerald_block',
  'redstone_torch',
  'lever',
  'stone_button',
  'repeater',
  'redstone_lamp',
  'observer',
  'comparator',
  'dispenser',
  'hopper',
  'end_stone',
  'end_portal_frame',
  'end_portal_frame_filled',
  'chorus_flower',
  'chorus_plant',
  'dragon_egg',
  'end_crystal',
  'end_rod',
  'end_stone_bricks',
  'ender_chest',
  'purpur_block',
  'purpur_pillar',
  'purpur_slab',
  'purpur_stairs',
  'shulker_box',
  'crafting_table',
  'furnace',
  'chest',
  'door',
  'oak_stairs',
  'anvil',
  'cauldron',
  'bed',
  'enchanting_table',
  'brewing_stand',
  'tnt',
  'nether_brick',
  'netherrack',
  'raw_iron',
  'raw_gold',
  'diamond',
  'emerald',
  'lapis_lazuli',
  'redstone_dust',
  'amethyst_shard',
  'wheat_seeds',
  'potato',
  'nether_wart',
  'ladder',
  'kelp',
  'seagrass',
  'rail',
  'powered_rail',
  'pressure_plate',
  'stone_slab',
  'string',
  'snowball',
] as const

export type ItemType = (typeof ITEM_TYPES)[number]
export type PlaceableItemType = Extract<ItemType, BlockType>
export type ItemStackType = ItemType | BlockType

const ITEM_TYPE_SET: ReadonlySet<string> = new Set(ITEM_TYPES)

export const isItemType = (value: string): value is ItemType => ITEM_TYPE_SET.has(value)
