import type { FeatureEvidence, FeatureRecord } from './feature-inventory'

/** Static cross-repository feature records; validation lives in feature-inventory.ts. */
const source = (repository: string, path: string, note: string): FeatureEvidence => ({
  repository,
  path,
  kind: 'source',
  note,
})

const test = (repository: string, path: string, note: string): FeatureEvidence => ({
  repository,
  path,
  kind: 'test',
  note,
})

const documentation = (repository: string, path: string, note: string): FeatureEvidence => ({
  repository,
  path,
  kind: 'documentation',
  note,
})

const gate = (repository: string, path: string, note: string): FeatureEvidence => ({
  repository,
  path,
  kind: 'gate',
  note,
})

/**
 * Cross-repository implementation inventory.
 *
 * Runtime behavior remains in the owning package. This catalog is deliberately
 * data-only: it records what is implemented, what is still partial, and which
 * contracts belong in mc-kernel or in this workspace binder.
 */
export const FEATURE_INVENTORY: ReadonlyArray<FeatureRecord> = [
  {
    id: 'meta/repository-roster',
    owner: 'mc-dev-meta',
    scope: 'workspace-tooling',
    status: 'implemented',
    summary: 'The authoritative repository roster and dependency graph.',
    management: 'meta-contract',
    evidence: [
      source('mc-dev-meta', 'src/domain/repository-roster.ts', 'Root-owned repository catalog.'),
      test('mc-dev-meta', 'test/roster.test.ts', 'Roster and graph invariants.'),
    ],
  },
  {
    id: 'meta/manifest-pins',
    owner: 'mc-dev-meta',
    scope: 'workspace-tooling',
    status: 'implemented',
    summary: 'Pinned repository manifest and sync decisions.',
    management: 'meta-contract',
    evidence: [
      source('mc-dev-meta', 'src/domain/manifest.ts', 'Manifest parser and pin contract.'),
      test('mc-dev-meta', 'test/manifest.test.ts', 'Manifest validation tests.'),
    ],
  },
  {
    id: 'meta/mirror-contracts',
    owner: 'mc-dev-meta',
    scope: 'workspace-tooling',
    status: 'implemented',
    summary: 'Cross-repository mirror and kernel vocabulary checks.',
    management: 'meta-contract',
    evidence: [
      source('mc-dev-meta', 'src/domain/mirror-contract.ts', 'Mirror decision contract.'),
      test('mc-dev-meta', 'test/mirror-contract.test.ts', 'Mirror contract tests.'),
    ],
  },
  {
    id: 'meta/repoint-plan',
    owner: 'mc-dev-meta',
    scope: 'workspace-tooling',
    status: 'implemented',
    summary: 'Throwaway-copy verification for dependency repointing.',
    management: 'meta-contract',
    evidence: [
      source('mc-dev-meta', 'src/domain/repoint-plan.ts', 'Repoint decision model.'),
      test('mc-dev-meta', 'test/repoint-plan.test.ts', 'Repoint plan tests.'),
    ],
  },
  {
    id: 'meta/feature-inventory',
    owner: 'mc-dev-meta',
    scope: 'workspace-tooling',
    status: 'implemented',
    summary: 'Typed ownership and implementation inventory for all repositories.',
    management: 'meta-contract',
    evidence: [
      source('mc-dev-meta', 'src/domain/feature-catalog.ts', 'Static feature catalog.'),
      test('mc-dev-meta', 'test/feature-inventory.test.ts', 'Catalog invariant tests.'),
    ],
  },
  {
    id: 'kernel/block-vocabulary',
    owner: 'mc-kernel',
    scope: 'kernel-contract',
    status: 'implemented',
    summary: 'Canonical block identifiers, definitions, and registry lookups.',
    management: 'kernel-canonical',
    evidence: [
      source('mc-kernel', 'src/domain/block-registry.ts', 'Kernel block registry.'),
      test('mc-kernel', 'test/block-registry.test.ts', 'Registry and lookup tests.'),
    ],
  },
  {
    id: 'kernel/block-capabilities',
    owner: 'mc-kernel',
    scope: 'kernel-contract',
    status: 'implemented',
    summary: 'Shared block capability flags and harvesting rules.',
    management: 'kernel-canonical',
    evidence: [
      source('mc-kernel', 'src/domain/block-capabilities.ts', 'Canonical capability model.'),
      test('mc-kernel', 'test/block-capabilities.test.ts', 'Capability behavior tests.'),
    ],
  },
  {
    id: 'kernel/frame-clock-contract',
    owner: 'mc-kernel',
    scope: 'kernel-contract',
    status: 'implemented',
    summary: 'Shared frame ordering and Clock Port contract.',
    management: 'kernel-canonical',
    evidence: [
      source('mc-kernel', 'src/domain/frame.ts', 'Frame contract.'),
      source('mc-kernel', 'src/domain/clock.ts', 'Clock Port.'),
      test('mc-kernel', 'test/clock-and-frame.test.ts', 'Frame and clock tests.'),
    ],
  },
  {
    id: 'meta/portable-voxel-chunk',
    owner: 'mc-dev-meta',
    scope: 'portable-contract',
    status: 'implemented',
    summary: 'Portable Y-major chunk data and deterministic one-byte block codec.',
    management: 'portable-canonical',
    evidence: [
      source('mc-dev-meta', 'src/domain/voxel-chunk.ts', 'Portable chunk data and wire codec.'),
      test('mc-dev-meta', 'test/voxel-chunk.test.ts', 'Chunk layout, validation, and codec tests.'),
      documentation('mc-dev-meta', 'docs/portable-chunk.md', 'Portable chunk ownership and format.'),
    ],
  },
  {
    id: 'meta/portable-light-grid',
    owner: 'mc-dev-meta',
    scope: 'portable-contract',
    status: 'implemented',
    summary: 'Portable packed sky/block light grids and nibble access contract.',
    management: 'portable-canonical',
    evidence: [
      source('mc-dev-meta', 'src/domain/light-grid.ts', 'Portable two-grid four-bit light storage.'),
      test('mc-dev-meta', 'test/light-grid.test.ts', 'Packing, clamping, cloning, and validation tests.'),
      documentation('mc-dev-meta', 'docs/portable-light-grid.md', 'Portable light-grid ownership and format.'),
      gate('mc-dev-meta', 'scripts/check-portable-contract.ts', 'Runtime parity with mc-worldgen light storage and kernel vocabulary.'),
    ],
  },
  {
    id: 'noise/deterministic-fields',
    owner: 'mc-noise',
    scope: 'stable-library',
    status: 'implemented',
    summary: 'Seeded deterministic noise fields and octave composition.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-noise', 'src/domain/perlin.ts', 'Deterministic noise implementation.'),
      test('mc-noise', 'test/determinism.test.ts', 'Determinism invariants.'),
    ],
  },
  {
    id: 'physics/collision-resolution',
    owner: 'mc-physics',
    scope: 'stable-library',
    status: 'implemented',
    summary: 'AABB collision resolution and time-step integration.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-physics', 'src/domain/resolve.ts', 'Collision resolver.'),
      test('mc-physics', 'test/resolve.test.ts', 'Collision resolution tests.'),
    ],
  },
  {
    id: 'meshing/voxel-geometry',
    owner: 'mc-meshing',
    scope: 'stable-library',
    status: 'implemented',
    summary: 'Voxel-to-mesh conversion with greedy merge and preserved coverage invariants.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-meshing', 'src/domain/mesh.ts', 'Mesh conversion API.'),
      test('mc-meshing', 'test/mesh.test.ts', 'Mesh conversion tests.'),
      documentation('mc-meshing', 'docs/public-api.md', 'Greedy merge contract and naive oracle.'),
    ],
  },
  {
    id: 'meshing/fluid-and-ao-meshes',
    owner: 'mc-meshing',
    scope: 'stable-library',
    status: 'implemented',
    summary: 'Fluid mesh and ambient-occlusion support for meshing consumers.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-meshing', 'src/domain/fluid-mesh.ts', 'Fluid mesh rules.'),
      source('mc-meshing', 'src/domain/ambient-occlusion.ts', 'Ambient occlusion rules.'),
      test('mc-meshing', 'test/fluid-mesh.test.ts', 'Fluid mesh tests.'),
      test('mc-meshing', 'test/ambient-occlusion.test.ts', 'Ambient occlusion tests.'),
    ],
  },
  {
    id: 'save/versioned-persistence',
    owner: 'mc-save',
    scope: 'stable-library',
    status: 'implemented',
    summary: 'Versioned save envelopes, migration, and IndexedDB storage ports.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-save', 'src/domain/envelope.ts', 'Versioned save envelope.'),
      test('mc-save', 'test/format-roundtrip.test.ts', 'Format round-trip tests.'),
      test('mc-save', 'test/migration.test.ts', 'Migration tests.'),
    ],
  },
  {
    id: 'audio/webaudio-surface',
    owner: 'mc-audio',
    scope: 'stable-library',
    status: 'implemented',
    summary:
      'WebAudio surface, placeholder cue synthesis, music, captions, and terminal soundboard preview; sample assets remain outside this scope.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-audio', 'src/domain/webaudio-surface.ts', 'WebAudio integration surface.'),
      source('mc-audio', 'src/domain/webaudio-adapter.ts', 'WebAudio adapter.'),
      test('mc-audio', 'test/webaudio-surface.test.ts', 'Surface tests.'),
      test('mc-audio', 'test/soundboard-preview.test.ts', 'Soundboard preview tests.'),
      documentation(
        'mc-audio',
        'docs/responsibility.md',
        'Scoped implementation and sample-asset boundary.',
      ),
    ],
  },
  {
    id: 'worldgen/terrain-and-biomes',
    owner: 'mc-worldgen',
    scope: 'foundation',
    status: 'implemented',
    summary: 'Seeded terrain, biome distribution, trees, ores, and carvers.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-worldgen', 'src/domain/terrain.ts', 'Terrain generation.'),
      source('mc-worldgen', 'src/domain/biome.ts', 'Biome model.'),
      test('mc-worldgen', 'test/terrain-levels.test.ts', 'Terrain level tests.'),
      test('mc-worldgen', 'test/biome-and-trees.test.ts', 'Biome and tree tests.'),
    ],
  },
  {
    id: 'worldgen/chunks-light-structures',
    owner: 'mc-worldgen',
    scope: 'foundation',
    status: 'partial',
    summary: 'Chunk lifecycle, light, and structure siting are present with documented generation and persistence gaps.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-worldgen', 'src/domain/chunk.ts', 'Chunk lifecycle model.'),
      source('mc-worldgen', 'src/domain/light.ts', 'Light model.'),
      source('mc-worldgen', 'src/domain/structure-siting.ts', 'Structure siting.'),
      test('mc-worldgen', 'test/chunk-store.test.ts', 'Chunk store tests.'),
      test('mc-worldgen', 'test/light.test.ts', 'Light tests.'),
      test('mc-worldgen', 'test/structure-siting.test.ts', 'Structure siting tests.'),
      documentation('mc-worldgen', 'docs/README.md', 'Remaining structure, light-grid, and persistence notes.'),
    ],
  },
  {
    id: 'sim/core-state-and-time',
    owner: 'mc-sim',
    scope: 'foundation',
    status: 'implemented',
    summary: 'Entity, inventory, crafting, settings, and time-of-day state services.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-sim', 'src/domain/entity.ts', 'Entity model.'),
      source('mc-sim', 'src/domain/inventory.ts', 'Inventory model.'),
      source('mc-sim', 'src/domain/time-of-day.ts', 'Time-of-day model.'),
      test('mc-sim', 'test/entity.test.ts', 'Entity tests.'),
      test('mc-sim', 'test/inventory.test.ts', 'Inventory tests.'),
      test('mc-sim', 'test/time-of-day.test.ts', 'Time tests.'),
    ],
  },
  {
    id: 'sim/survival-progression',
    owner: 'mc-sim',
    scope: 'foundation',
    status: 'partial',
    summary:
      'Vitals, statistics, and achievement tracking (record-only; unlock predicates are mx-gameplay\'s) are implemented and tested; the remaining gap is enchant rules and official brewing recipes outside the current mc-kernel ItemType vocabulary.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-sim', 'src/domain/vitals.ts', 'Vitals model.'),
      source('mc-sim', 'src/domain/statistics.ts', 'Statistics and achievement-record model.'),
      source('mc-sim', 'src/application/statistics-service.ts', 'Achievement-unlock persistence service.'),
      test('mc-sim', 'test/vitals.test.ts', 'Vitals tests.'),
      test('mc-sim', 'test/statistics.test.ts', 'Statistics and achievement tests.'),
      documentation('mc-sim', 'docs/responsibility.md', 'Achievement tracking scoped and documented as implemented.'),
      documentation('mc-sim', 'docs/README.md', 'Enchant-rule and official-brewing-recipe gap outside the current mc-kernel ItemType vocabulary.'),
    ],
  },
  {
    id: 'render/renderer-and-input',
    owner: 'mc-render',
    scope: 'foundation',
    status: 'partial',
    summary:
      'Core chunk rendering, camera/input bindings, touch input, dirty-chunk sync, light application, gamepad input, and stage registration are implemented and tested; keyboard focus navigation within a group and some quality-preset knobs (shadow resolution, render scale) remain open.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-render', 'src/domain/chunk-geometry.ts', 'Chunk geometry.'),
      source('mc-render', 'src/domain/input-bindings.ts', 'Input bindings.'),
      source('mc-render', 'src/domain/gamepad-input.ts', 'Gamepad input model.'),
      test('mc-render', 'test/world-renderer.test.ts', 'Renderer tests.'),
      test('mc-render', 'test/input.test.ts', 'Input tests.'),
      test('mc-render', 'test/gamepad-input.test.ts', 'Gamepad input tests.'),
      test('mc-render', 'test/touch-controls.test.ts', 'Touch control tests.'),
      documentation('mc-render', 'README.md', 'Runtime integration boundaries.'),
      documentation('mc-render', 'docs/responsibility.md', 'Focus-navigation and quality-preset gaps.'),
    ],
  },
  {
    id: 'render/advanced-effects',
    owner: 'mc-render',
    scope: 'foundation',
    status: 'partial',
    summary:
      'Particle, water, voxel-lighting, and post-processing policies are tested and wired to real THREE.js — ShaderMaterial, EffectComposer, and TextureLoader are all integrated in src/browser.ts; only the literal THREE.InstancedMesh class remains unused, since particle instancing is built directly on InstancedBufferGeometry/InstancedBufferAttribute instead.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-render', 'src/domain/particle-pool.ts', 'Particle pool.'),
      source('mc-render', 'src/domain/water-surface.ts', 'Water surface.'),
      source('mc-render', 'src/domain/voxel-lighting.ts', 'Voxel lighting.'),
      source('mc-render', 'src/browser.ts', 'Real THREE.js wiring: ShaderMaterial, EffectComposer, TextureLoader.'),
      test('mc-render', 'test/particle-pool.test.ts', 'Particle tests.'),
      test('mc-render', 'test/water-surface.test.ts', 'Water tests.'),
      test('mc-render', 'test/voxel-lighting.test.ts', 'Lighting tests.'),
      test('mc-render', 'test/particle-system.test.ts', 'THREE-integrated particle system tests.'),
      test('mc-render', 'test/world-renderer-materials.test.ts', 'THREE material integration tests.'),
      test('mc-render', 'test/world-renderer-production.test.ts', 'Production world-renderer integration tests.'),
      documentation('mc-render', 'README.md', 'Remaining renderer adapters.'),
      documentation('mc-render', 'docs/responsibility.md', 'Open advanced-effects responsibilities.'),
    ],
  },
  {
    id: 'playground/preview-harness',
    owner: 'mc-playground-kit',
    scope: 'foundation',
    status: 'implemented',
    summary: 'Shared preview launch and boot phases for downstream packages.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-playground-kit', 'src/domain/boot-phase.ts', 'Preview boot state.'),
      test('mc-playground-kit', 'test/playground.test.ts', 'Preview harness tests.'),
      documentation('mc-playground-kit', 'docs/responsibility.md', 'Preview responsibility boundary.'),
    ],
  },
  {
    id: 'gameplay/block-interactions',
    owner: 'mx-gameplay',
    scope: 'experience',
    status: 'implemented',
    summary: 'Mining, placement, block loot, item use, portals, and interaction rules.',
    management: 'downstream-runtime',
    evidence: [
      source('mx-gameplay', 'src/domain/interactions/place-block.ts', 'Block placement interaction.'),
      source('mx-gameplay', 'src/domain/interactions/block-loot.ts', 'Block loot interaction.'),
      test('mx-gameplay', 'test/place-block.test.ts', 'Placement tests.'),
      test('mx-gameplay', 'test/block-loot.test.ts', 'Loot tests.'),
    ],
  },
  {
    id: 'gameplay/mobs-fluids-vehicles',
    owner: 'mx-gameplay',
    scope: 'experience',
    status: 'partial',
    summary: 'Mob, fluid, vehicle, day-night, weather, and falling-block rules.',
    management: 'downstream-runtime',
    evidence: [
      source('mx-gameplay', 'src/domain/mob/mob-drop.ts', 'Mob drop rules.'),
      source('mx-gameplay', 'src/domain/fluid-frontier.ts', 'Fluid frontier.'),
      source('mx-gameplay', 'src/domain/vehicle/rail-shape.ts', 'Vehicle rail shape.'),
      test('mx-gameplay', 'test/mob.test.ts', 'Mob tests.'),
      test('mx-gameplay', 'test/rail.test.ts', 'Vehicle rail tests.'),
      test('mx-gameplay', 'test/day-night.test.ts', 'Day-night tests.'),
      test('mx-gameplay', 'test/weather.test.ts', 'Weather tests.'),
      documentation('mx-gameplay', 'README.md', 'Responsibility status and remaining gameplay scope.'),
    ],
  },
  {
    id: 'redstone/power-and-devices',
    owner: 'mx-redstone',
    scope: 'experience',
    status: 'partial',
    summary: 'Power graph, comparators, observers, dispensers, hoppers, and pressure plates. For the latter three, only the redstone-rule slice (lock inversion, transfer cadence, rising edge, occupant count to signal strength) is implemented here; item and entity interaction is deliberately out of scope for this module, not a gap.',
    management: 'downstream-runtime',
    evidence: [
      source('mx-redstone', 'src/domain/power-graph.ts', 'Power propagation graph.'),
      source('mx-redstone', 'src/domain/comparator.ts', 'Comparator rules.'),
      source('mx-redstone', 'src/domain/pressure-plate.ts', 'Occupant-count-to-signal rule; occupancy itself is supplied by the caller.'),
      test('mx-redstone', 'test/power-graph.test.ts', 'Power graph tests.'),
      test('mx-redstone', 'test/comparator.test.ts', 'Comparator tests.'),
      documentation('mx-redstone', 'README.md', 'Hopper, dispenser, and pressure-plate rows: only the redstone-rule slice is complete here; item/entity interaction is named as out of scope, with the missing types and queries tabulated in docs/design-notes.md DN-RS-17.'),
    ],
  },
  {
    id: 'redstone/repeater-and-sticky-piston',
    owner: 'mx-redstone',
    scope: 'experience',
    status: 'partial',
    summary: 'Repeater delay, button pulse, piston push planning, and sticky-piston pull planning are implemented against the kernel block capability and adhesion contract; world mutation remains downstream.',
    management: 'downstream-runtime',
    evidence: [
      source('mx-redstone', 'src/domain/power-timing.ts', 'Repeater delay and button pulse state.'),
      test('mx-redstone', 'test/power-timing.test.ts', 'Repeater and button timing tests.'),
      source('mx-redstone', 'src/domain/piston.ts', 'Push and pull plans consume kernel-owned piston capabilities and adhesion properties.'),
      test('mx-redstone', 'test/piston.test.ts', 'Push limit, immovable blocks, sticky carriers, and slime/honey adhesion boundaries.'),
      documentation('mx-redstone', 'README.md', 'Piston push and sticky-piston pull planning are implemented; world mutation remains outside the module.'),
      documentation('mx-redstone', 'docs/design-notes.md', 'DN-RS-10 records the kernel capability and adhesion contract used by sticky pulling.'),
      source('mc-kernel', 'src/domain/block-capabilities.ts', 'Kernel-owned pistonSticky and pistonImmovable capability flags.'),
      source('mc-kernel', 'src/domain/block-properties.ts', 'Kernel-owned pistonAdhesion property and PistonAdhesion type.'),
    ],
  },
  {
    id: 'ui/screens-and-hud',
    owner: 'mx-ui',
    scope: 'experience',
    status: 'partial',
    summary:
      'Screen, HUD, inventory, menu, accessibility, caption, and save-status view models plus a structural DOM surface exist, with browser accessibility verification complete (18 Playwright tests across real-DOM, real-pixel, and hit-target/focus-ring specs, mutation-tested); CSS/asset shipping and asset-aware publish remain open.',
    management: 'downstream-runtime',
    evidence: [
      source('mx-ui', 'src/domain/hud-view-model.ts', 'HUD view model.'),
      source('mx-ui', 'src/domain/main-menu.ts', 'Main menu view model.'),
      source('mx-ui', 'src/application/dom-surface.ts', 'Real DOM consumer surface.'),
      test('mx-ui', 'test/screen-views.test.ts', 'Screen view tests.'),
      test('mx-ui', 'test/accessibility.test.ts', 'Accessibility tests.'),
      test('mx-ui', 'test-browser/dom-surface.spec.ts', 'Real-DOM Playwright accessibility verification.'),
      test('mx-ui', 'test-browser/palette-pixels.spec.ts', 'Real-pixel palette accessibility verification.'),
      test('mx-ui', 'test-browser/geometry.spec.ts', 'Hit-target and focus-ring geometry verification.'),
      documentation('mx-ui', 'docs/versioning.md', 'CSS/font/icon bundling and asset-aware publish are undecided.'),
      documentation('mx-ui', 'docs/responsibility.md', 'The DOM consumer, CSS/assets, and publish are not complete.'),
    ],
  },
  {
    id: 'multiplayer/protocol-and-transport',
    owner: 'mx-multiplayer',
    scope: 'experience',
    status: 'partial',
    summary:
      'Transport, connection lifecycle, and frame codec are implemented; the protocol schema is a structurally exhaustive 46-tag union with no incompleteness markers, but state synchronization remains an unimplemented mc-sim integration seam — no module in src/ imports @nerima-games/mc-sim.',
    management: 'downstream-runtime',
    evidence: [
      source('mx-multiplayer', 'src/domain/protocol.ts', 'Synchronization protocol.'),
      source('mx-multiplayer', 'src/domain/transport.ts', 'Transport contract.'),
      source('mx-multiplayer', 'src/stages/registration.ts', 'Inbound-frame queue seam; sim application deferred to an external host/session adapter.'),
      test('mx-multiplayer', 'test/transport.test.ts', 'Transport tests.'),
      test('mx-multiplayer', 'test/connection.test.ts', 'Connection tests.'),
      documentation('mx-multiplayer', 'docs/responsibility.md', 'State-synchronization integration with mc-sim is incomplete.'),
    ],
  },
  {
    id: 'compose/layers-stages-session',
    owner: 'mc-compose',
    scope: 'composition',
    status: 'implemented',
    summary: 'Layer composition, stage order, session lifecycle, QA API, and modding entry points.',
    management: 'downstream-runtime',
    evidence: [
      source('mc-compose', 'src/domain/composition.ts', 'Layer composition.'),
      source('mc-compose', 'src/domain/stage-order.ts', 'Stage ordering.'),
      source('mc-compose', 'src/domain/session.ts', 'Session lifecycle.'),
      test('mc-compose', 'test/composition.test.ts', 'Composition tests.'),
      test('mc-compose', 'test/stage-order.test.ts', 'Stage order tests.'),
    ],
  },
  {
    id: 'compose/end-to-end-gate',
    owner: 'mc-compose',
    scope: 'composition',
    status: 'partial',
    summary: 'Roster E2E coverage exists, while the final end-to-end gate is still tracked as incomplete.',
    management: 'downstream-runtime',
    evidence: [
      test('mc-compose', 'test/e2e/roster-frame-order.test.ts', 'Roster frame-order E2E test.'),
      documentation('mc-compose', 'README.md', 'Final E2E gate status.'),
      documentation('mc-compose', 'docs/README.md', 'Composition verification status.'),
    ],
  },
] as const
