import type { FeatureSpec } from './feature-audit'

/**
 * Evidence-backed obligations for the portable feature surface.
 *
 * `requiredPaths` are repository-root-relative paths in this checkout. The
 * owner records the managed repository that supplied the rule or contract;
 * the audit intentionally reads the consolidated implementation here rather
 * than depending on an optional `repos/` checkout.
 */
export const FEATURE_SPECS: ReadonlyArray<FeatureSpec> = [
  {
    id: 'kernel.block-registry',
    owner: 'mc-kernel',
    title: 'ブロック ID レジストリと属性解決',
    requiredPaths: ['src/kernel/block-registry.ts'],
    implementationMarkers: ['export const BLOCK_ID_MAX', 'export const BLOCK_IDS', 'export const blockDefinitionOf'],
    gapMarkers: [],
  },
  {
    id: 'kernel.harvest-drops',
    owner: 'mc-kernel',
    title: '採掘条件とブロックドロップ解決',
    requiredPaths: ['src/kernel/block-harvest.ts'],
    implementationMarkers: ['export type BlockDropRule', 'export const resolveDrop', 'export const resolveHarvestDrop'],
    gapMarkers: [],
  },
  {
    id: 'kernel.silk-touch-substitution',
    owner: 'mc-kernel',
    title: 'シルクタッチによるドロップ置換',
    requiredPaths: ['src/kernel/block-harvest.ts'],
    implementationMarkers: ['silkTouchItem', 'context.silkTouch === true', 'export const resolveDropItem'],
    gapMarkers: [],
  },
  {
    id: 'kernel.block-capabilities-and-properties',
    owner: 'mc-kernel',
    title: 'ブロック能力・足音・耕地・テクスチャ属性',
    requiredPaths: ['src/kernel/block-capabilities.ts', 'src/kernel/block-properties.ts'],
    implementationMarkers: [
      'export type BlockCapabilities',
      'export type FootstepMaterial',
      'readonly tillable',
      'export type TextureTiles',
    ],
    gapMarkers: [],
  },
  {
    id: 'kernel.block-support',
    owner: 'mc-kernel',
    title: 'ブロック付着の支持判定',
    requiredPaths: ['src/kernel/block-support.ts'],
    implementationMarkers: ['export const supportsAttachment'],
    gapMarkers: [],
  },
  {
    id: 'physics.coordinates-and-collision-primitives',
    owner: 'mc-physics',
    title: '座標・チャンク・AABB の純粋プリミティブ',
    requiredPaths: ['src/kernel/coordinates.ts', 'src/kernel/chunk.ts'],
    implementationMarkers: ['export const aabbIntersects', 'export const getBlockAt', 'export const chunkKey'],
    gapMarkers: [],
  },
  {
    id: 'worldgen.noise',
    owner: 'mc-noise',
    title: '決定的ノイズ・octave・地形チャンネル',
    requiredPaths: [
      'src/kernel/noise-seed.ts',
      'src/kernel/noise-perlin.ts',
      'src/kernel/noise-octaves.ts',
      'src/kernel/noise-field.ts',
    ],
    implementationMarkers: [
      'export const mulberry32',
      'export const createPerlinNoise2D',
      'export const octaveNoise2D',
      'export const createNoiseField',
    ],
    gapMarkers: [],
  },
  {
    id: 'gameplay.raycast',
    owner: 'mc-physics',
    title: 'ブロック視線レイキャスト',
    requiredPaths: ['src/kernel/raycast.ts'],
    implementationMarkers: ['export const raycastBlocks', 'export const normalizeDirection'],
    gapMarkers: [],
  },
  {
    id: 'gameplay.fluid-propagation',
    owner: 'mx-gameplay',
    title: '流体セル・近傍・伝播ルール',
    requiredPaths: ['src/kernel/fluid.ts'],
    implementationMarkers: ['export const fluidNeighboursOf', 'export const flowInto', 'export const splitFluidBudget'],
    gapMarkers: [],
  },
  {
    id: 'gameplay.day-night',
    owner: 'mx-gameplay',
    title: '昼夜・薄明・敵対的スポーン判定',
    requiredPaths: ['src/kernel/day-night.ts'],
    implementationMarkers: ['export const dayPhase', 'export const hostileSpawnsAllowed'],
    gapMarkers: [],
  },
  {
    id: 'gameplay.block-placement',
    owner: 'mx-gameplay',
    title: '面へのブロック設置と支持判定',
    requiredPaths: ['src/kernel/block-placement.ts'],
    implementationMarkers: ['export const placeBlock'],
    gapMarkers: [],
  },
  {
    id: 'sim.inventory-and-crafting',
    owner: 'mc-sim',
    title: 'インベントリ・スタック・クラフト純粋ルール',
    requiredPaths: ['src/kernel/inventory.ts', 'src/kernel/crafting.ts'],
    implementationMarkers: ['export const addItemStack', 'export const craftRecipe'],
    gapMarkers: [],
  },
  {
    id: 'redstone.components',
    owner: 'mx-redstone',
    title: 'コンパレーター・コンテナ・感圧板',
    requiredPaths: ['src/kernel/redstone-comparator.ts', 'src/kernel/redstone-plate.ts'],
    implementationMarkers: [
      'export const comparatorOutput',
      'export const containerSignalStrength',
      'export const plateSignal',
    ],
    gapMarkers: [],
  },
  {
    id: 'redstone.propagation',
    owner: 'mx-redstone',
    title: 'レッドストーン信号の減衰・伝播',
    requiredPaths: ['src/kernel/redstone.ts'],
    implementationMarkers: ['export const propagateRedstonePower', 'export const decayPower'],
    gapMarkers: [],
  },
  {
    id: 'redstone.piston-push',
    owner: 'mx-redstone',
    title: 'ピストン押出し制約',
    requiredPaths: ['src/kernel/piston.ts'],
    implementationMarkers: ['export const planPistonPush', 'export const isPistonMovable'],
    gapMarkers: [],
  },
  {
    id: 'redstone.timing-and-sticky-pistons',
    owner: 'mx-redstone',
    title: 'レッドストーン遅延・パルス・粘着ピストン',
    requiredPaths: ['src/kernel/redstone-timing.ts', 'src/kernel/sticky-piston.ts'],
    implementationMarkers: ['export const propagateTick', 'export const planStickyPistonMove'],
    gapMarkers: [],
  },
  {
    id: 'worldgen.biomes-and-placements',
    owner: 'mc-worldgen',
    title: 'バイオーム・鉱石・樹木配置ルール',
    requiredPaths: ['src/kernel/biome.ts', 'src/kernel/ore-placement.ts', 'src/kernel/tree-placement.ts'],
    implementationMarkers: ['export const biomeAt', 'export const placeOre', 'export const placeTree'],
    gapMarkers: [],
  },
  {
    id: 'worldgen.structures-and-dimensions',
    owner: 'mc-worldgen',
    title: '構造物・村・End 次元の生成',
    requiredPaths: ['src/kernel/worldgen-structures.ts', 'src/kernel/dimensions.ts'],
    implementationMarkers: ['export const generateStructure', 'export const dimensionRulesOf'],
    gapMarkers: [],
  },
  {
    id: 'worldgen.chunk-persistence',
    owner: 'mc-worldgen',
    title: 'チャンクの永続化フォーマット',
    requiredPaths: ['src/kernel/chunk-persistence.ts'],
    implementationMarkers: ['export const encodeChunk', 'export const decodeChunk'],
    gapMarkers: [],
  },
  {
    id: 'save.chunk-format',
    owner: 'mc-save',
    title: '保存層とチャンクスナップショット契約',
    requiredPaths: ['src/kernel/save-format.ts'],
    implementationMarkers: ['export const encodeSave', 'export const decodeSave'],
    gapMarkers: [],
  },
  {
    id: 'meshing.advanced-geometry',
    owner: 'mc-meshing',
    title: 'AO・流体形状・植生・差分メッシュ',
    requiredPaths: ['src/kernel/mesh.ts'],
    implementationMarkers: ['export const meshChunk', 'export const ambientOcclusion'],
    gapMarkers: [],
  },
  {
    id: 'render.runtime-integration',
    owner: 'mc-render',
    title: 'ダーティチャンク購読・実行時入力・アトラス適用',
    requiredPaths: ['src/render/world-renderer.ts'],
    implementationMarkers: ['export class WorldRenderer'],
    gapMarkers: [],
  },
  {
    id: 'audio.browser-adapter',
    owner: 'mc-audio',
    title: 'WebAudio アダプタとサウンドボード',
    requiredPaths: ['src/audio/audio-backend.ts'],
    implementationMarkers: ['export interface AudioBackendPort'],
    gapMarkers: [],
  },
  {
    id: 'compose.e2e',
    owner: 'mc-compose',
    title: '構成層の E2E 最終ゲート',
    requiredPaths: ['test/e2e/compose.test.ts'],
    implementationMarkers: ['describe(', 'compose'],
    gapMarkers: [],
  },
  {
    id: 'multiplayer.websocket-adapter',
    owner: 'mx-multiplayer',
    title: '実 WebSocket トランスポートアダプタ',
    requiredPaths: ['src/multiplayer/websocket-transport.ts'],
    implementationMarkers: ['export class WebSocketTransport'],
    gapMarkers: [],
  },
]
